# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Visual Studio 9 2008")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "ZIP")
SET(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp$;\\.#;/#")
SET(CPACK_INSTALLED_DIRECTORIES "C:/PFC/SlicerModules/MyExtension;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/MyExtension")
SET(CPACK_MODULE_PATH "C:/SlicerPFC/SlicerExecutionModel-build/CMake;C:/SlicerPFC/SlicerExecutionModel-build/CMake;C:/SlicerPFC/SlicerExecutionModel-build/CMake;C:/SlicerPFC/VTKv6/CMake;C:/SlicerPFC/ITKv4/Modules/ThirdParty/DCMTK/CMake;C:/SlicerPFC/CTK/Utilities/CMake;C:/SlicerPFC/CTK/CMake;C:/SlicerPFC/CTK/Utilities/CMake;C:/PFC/Slicer/CMake;C:/PFC/Slicer/Extensions/CMake;C:/SlicerPFC/VTKv6/CMake")
SET(CPACK_MONOLITHIC_INSTALL "ON")
SET(CPACK_NSIS_DISPLAY_NAME "MyExtension 0.1.1")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_MODIFY_PATH "OFF")
SET(CPACK_NSIS_PACKAGE_NAME "MyExtension 0.1.1")
SET(CPACK_OUTPUT_CONFIG_FILE "C:/PFC/SlicerModules/MyExtension/Vs2008Build/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "C:/PFC/Slicer/README.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "This is an example of a simple extension")
SET(CPACK_PACKAGE_FILE_NAME "MyExtension-0.1.1-Source")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "MyExtension 0.1.1")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "MyExtension 0.1.1")
SET(CPACK_PACKAGE_NAME "MyExtension")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "NA-MIC")
SET(CPACK_PACKAGE_VERSION "0.1.1")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "C:/PFC/Slicer/License.txt")
SET(CPACK_RESOURCE_FILE_README "C:/Program Files (x86)/CMake/share/cmake-3.0/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files (x86)/CMake/share/cmake-3.0/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "ZIP")
SET(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp$;\\.#;/#")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "C:/PFC/SlicerModules/MyExtension;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/PFC/SlicerModules/MyExtension/Vs2008Build/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "MyExtension-0.1.1-Source")
SET(CPACK_SOURCE_TBZ2 "OFF")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "win32-Source")
SET(CPACK_SOURCE_TZ "OFF")
SET(CPACK_SOURCE_ZIP "ON")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "win32")
SET(CPACK_TOPLEVEL_TAG "win32-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "4")
