set(CTEST_CMAKE_GENERATOR "Visual Studio 9 2008")
set(GIT_EXECUTABLE "C:/Program Files (x86)/Git/cmd/git.exe")
set(Subversion_SVN_EXECUTABLE "C:/Program Files/SlikSvn/bin/svn.exe")
set(CMAKE_MAKE_PROGRAM "C:/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/IDE/VCExpress.exe")
set(CMAKE_C_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/bin/cl.exe")
set(CMAKE_CXX_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/bin/cl.exe")
set(BUILD_TESTING "ON")
set(RUN_CTEST_SUBMIT "TRUE")
set(EXTENSION_BUILD_OPTIONS_STRING "32bits-Qt4.8")
set(EXTENSION_COMPILER "VCExpress")
set(EXTENSION_NAME "MyExtension")
set(EXTENSION_CATEGORY "Examples")
set(EXTENSION_STATUS "")
set(EXTENSION_ICONURL "http://www.example.com/Slicer/Extensions/MyExtension.png")
set(EXTENSION_CONTRIBUTORS "John Doe (AnyWare Corp.)")
set(EXTENSION_DESCRIPTION "This is an example of a simple extension")
set(EXTENSION_HOMEPAGE "http://www.example.com/Slicer/Extensions/MyExtension")
set(EXTENSION_SCREENSHOTURLS "http://www.example.com/Slicer/Extensions/MyExtension/Screenshots/1.png")
set(EXTENSION_SOURCE_DIR "C:/PFC/SlicerModules/MyExtension")
set(EXTENSION_SUPERBUILD_BINARY_DIR "C:/PFC/SlicerModules/MyExtension/Vs2008Build")
set(EXTENSION_BUILD_SUBDIRECTORY ".")
set(EXTENSION_ENABLED "1")
set(EXTENSION_DEPENDS "NA")
set(Slicer_CMAKE_DIR "C:/PFC/Slicer/CMake")
set(Slicer_DIR "C:/SlicerPFC/Slicer-build")
set(Slicer_EXTENSIONS_TRACK_QUALIFIER "master")
set(Slicer_WC_REVISION "594fe76")
set(MIDAS_PACKAGE_URL "http://slicer.kitware.com/midas3")
set(MIDAS_PACKAGE_EMAIL "YOUR-MIDAS-LOGIN-NOTFOUND")
set(MIDAS_PACKAGE_API_KEY "YOUR-MIDAS-APIKEY-NOTFOUND")
set(NA_DIR "")
set(RUN_CTEST_CONFIGURE "FALSE")
set(RUN_CTEST_BUILD "TRUE")
set(RUN_CTEST_TEST "TRUE")
set(RUN_CTEST_PACKAGES "TRUE")
set(RUN_CTEST_UPLOAD "FALSE")